export type CounterColor = 'red' | 'black';
export type CellState = CounterColor | 'empty';
export type FrameCapacity = 10 | 20;

export interface TenFrameGrid {
  readonly capacity: FrameCapacity;
  readonly cells: ReadonlyArray<CellState>;
  readonly redCount: number;
  readonly blackCount: number;
  readonly totalCount: number;
}

export type ProblemType = 'subitize' | 'number-bond' | 'equation';

/**
 * Base polymorphic domain problem contract.
 * All domain problem instances generated by math engines satisfy this interface.
 */
export interface BaseDomainProblem {
  readonly id: string;
  readonly type: ProblemType;
  validate(answer: number): boolean;
  getExpectedAnswer(): number;
}

export type SubitizeLayout = 'single' | 'double';

/**
 * Subitizing challenge problem interface.
 */
export interface SubitizeProblem extends BaseDomainProblem {
  readonly type: 'subitize';
  readonly targetCount: number;
  readonly redCount: number;
  readonly blackCount: number;
  readonly options: ReadonlyArray<number>; // Multiple choice answers
  readonly layout: SubitizeLayout;
  readonly grid?: TenFrameGrid;
}

export type DomainSubitizeProblem = SubitizeProblem;

export type NumberBondMissing = 'whole' | 'partA' | 'partB';

/**
 * Number bond challenge problem interface.
 */
export interface NumberBondProblem extends BaseDomainProblem {
  readonly type: 'number-bond';
  readonly whole: number;
  readonly partA: number;
  readonly partB: number;
  readonly missing: NumberBondMissing;
  readonly answer: number;
}

export type DomainNumberBondProblem = NumberBondProblem;

export type EquationOperator = '+' | '-';
export type EquationMissing = 'operand1' | 'operand2' | 'result';

/**
 * Arithmetic equation challenge problem interface.
 */
export interface EquationProblem extends BaseDomainProblem {
  readonly type: 'equation';
  readonly operand1: number;
  readonly operator: EquationOperator;
  readonly operand2: number;
  readonly result: number;
  readonly missing: EquationMissing;
  readonly answer: number;
  readonly isBridgingTen?: boolean;
}

export type DomainEquationProblem = EquationProblem;

/**
 * Discriminated union of all fully initialized domain problems.
 */
export type DomainProblem =
  | SubitizeProblem
  | NumberBondProblem
  | EquationProblem;

/**
 * Union of all active challenge problems (polymorphic domain problem or null).
 */
export type ActiveProblem =
  | DomainProblem
  | null;

/**
 * Helper to construct a fully polymorphic SubitizeProblem from plain data (useful for test fixtures).
 */
export function createSubitizeProblem(
  data: Omit<SubitizeProblem, 'type' | 'validate' | 'getExpectedAnswer'> & {
    type?: 'subitize';
    validate?: (answer: number) => boolean;
    getExpectedAnswer?: () => number;
  }
): SubitizeProblem {
  return {
    ...data,
    type: 'subitize',
    validate: data.validate ?? ((ans: number) => data.targetCount === ans),
    getExpectedAnswer: data.getExpectedAnswer ?? (() => data.targetCount),
  };
}

/**
 * Helper to construct a fully polymorphic NumberBondProblem from plain data.
 */
export function createNumberBondProblem(
  data: Omit<NumberBondProblem, 'type' | 'validate' | 'getExpectedAnswer'> & {
    type?: 'number-bond';
    validate?: (answer: number) => boolean;
    getExpectedAnswer?: () => number;
  }
): NumberBondProblem {
  const expectedAnswer =
    typeof data.answer === 'number'
      ? data.answer
      : data.missing === 'whole'
        ? data.whole
        : data.missing === 'partA'
          ? data.partA
          : data.partB;

  return {
    ...data,
    answer: expectedAnswer,
    type: 'number-bond',
    validate: data.validate ?? ((ans: number) => expectedAnswer === ans),
    getExpectedAnswer: data.getExpectedAnswer ?? (() => expectedAnswer),
  };
}

/**
 * Helper to construct a fully polymorphic EquationProblem from plain data.
 */
export function createEquationProblem(
  data: Omit<EquationProblem, 'type' | 'validate' | 'getExpectedAnswer'> & {
    type?: 'equation';
    validate?: (answer: number) => boolean;
    getExpectedAnswer?: () => number;
  }
): EquationProblem {
  const expectedAnswer =
    typeof data.answer === 'number'
      ? data.answer
      : data.missing === 'result'
        ? data.result
        : data.missing === 'operand1'
          ? data.operand1
          : data.operand2;

  return {
    ...data,
    answer: expectedAnswer,
    type: 'equation',
    validate: data.validate ?? ((ans: number) => expectedAnswer === ans),
    getExpectedAnswer: data.getExpectedAnswer ?? (() => expectedAnswer),
  };
}

export type ComparisonOperator = '<' | '=' | '>';

export interface ComparisonProblem {
  readonly id: string;
  readonly countA: number;
  readonly countB: number;
  readonly correctOperator: ComparisonOperator;
  readonly gridA: TenFrameGrid;
  readonly gridB: TenFrameGrid;
}
